services:
  nginx:
    image: rdzhei/croissant:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/sites.conf:/etc/nginx/conf.d/sites.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./../src/pdf:/app/dist/src/pdf
    networks:
      default: {}

