version: '3.6'
services:
  nginx:
    image: nginx:latest
    user: '1000:1000'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/sites-available
      - ./nginx:/etc/letsencrypt
    networks:
      default: {}

  croissant:
    image: rdzhei/croissant:latest
    networks:
      default: {}



