version: '3.6'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/sites-available
      - ./nginx:/etc/nginx/sites-enabled
      - ./nginx:/etc/letsencrypt
      - ./nginx/sites.conf:/etc/nginx/nginx.conf
    networks:
      default: {}

  croissant:
    image: rdzhei/croissant:latest
    networks:
      default: {}



