version: '3.6'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/sites.conf:/etc/nginx/conf.d/sites.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      default: {}

  croissant:
    image: rdzhei/croissant:latest
    networks:
      default: {}



